// 勞工人力日報 (G.F. 527 — Site Labour Return)
//
// Derived from the existing daily-log manpower data (dailies.manpower jsonb,
// [{trade, count}]) — SINGLE source of truth, no double entry. This module
// aggregates manpower over a period into a date × trade matrix and exports it in
// the G.F.527 labour-return shape (PDF + Excel). Reuses export.ts's
// shareOrDownloadBlob + ensureChineseFont (CJK glyphs).

import { shareOrDownloadBlob, ensureChineseFont } from './export'

export interface LabourDaily {
  date: string
  manpower: { trade: string; count: number }[] | null
}

export interface LabourReturnAgg {
  trades: string[]                                   // sorted union of trades seen
  dates: string[]                                    // sorted dates in range with data
  counts: Record<string, Record<string, number>>    // counts[date][trade]
  dateTotals: Record<string, number>
  tradeTotals: Record<string, number>
  grand: number
}

// Sum manpower per date per trade across all dailies in the period.
export function aggregateLabourReturn(rows: LabourDaily[]): LabourReturnAgg {
  const counts: Record<string, Record<string, number>> = {}
  const tradeSet = new Set<string>()
  const dateSet = new Set<string>()
  const tradeTotals: Record<string, number> = {}
  const dateTotals: Record<string, number> = {}
  let grand = 0

  for (const r of rows) {
    const mp = r.manpower ?? []
    if (mp.length === 0) continue
    for (const { trade, count } of mp) {
      const t = (trade ?? '').trim() || '其他'
      const n = Number(count) || 0
      if (n <= 0) continue
      dateSet.add(r.date)
      tradeSet.add(t)
      counts[r.date] = counts[r.date] || {}
      counts[r.date][t] = (counts[r.date][t] || 0) + n
      tradeTotals[t] = (tradeTotals[t] || 0) + n
      dateTotals[r.date] = (dateTotals[r.date] || 0) + n
      grand += n
    }
  }

  return {
    trades: Array.from(tradeSet).sort(),
    dates: Array.from(dateSet).sort(),
    counts,
    dateTotals,
    tradeTotals,
    grand,
  }
}

function safe(name: string): string {
  // Keep letters (incl. CJK) + digits + underscore; collapse everything else.
  return (name || 'project').replace(/[^\p{L}\p{N}_]+/gu, '_').slice(0, 40)
}

export async function exportLabourReturnExcel(projectName: string, period: string, agg: LabourReturnAgg): Promise<void> {
  const XLSX = await import('xlsx')
  const header = ['日期', ...agg.trades, '每日總計']
  const aoa: (string | number)[][] = [header]
  for (const d of agg.dates) {
    aoa.push([d, ...agg.trades.map(t => agg.counts[d]?.[t] ?? 0), agg.dateTotals[d] ?? 0])
  }
  aoa.push(['總計', ...agg.trades.map(t => agg.tradeTotals[t] ?? 0), agg.grand])

  const ws = XLSX.utils.aoa_to_sheet(aoa)
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, '勞工人力日報')
  const blob = new Blob([XLSX.write(wb, { type: 'array', bookType: 'xlsx' })], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  })
  await shareOrDownloadBlob(blob, `${safe(projectName)}_勞工人力日報_${period}.xlsx`, `勞工人力日報 ${period}`)
}

export async function exportLabourReturnPDF(projectName: string, period: string, agg: LabourReturnAgg): Promise<void> {
  const jspdfMod = await import('jspdf')
  const autoTableMod = await import('jspdf-autotable')
  const jsPDFCtor = (jspdfMod as any).default
  const autoTableFn = (autoTableMod as any).default

  // Landscape — the trade columns can be wide.
  const doc: any = new jsPDFCtor({ orientation: 'landscape', unit: 'pt', format: 'a4' })
  await ensureChineseFont(doc)

  doc.setFontSize(15)
  doc.text('勞工人力日報 (G.F. 527 — Site Labour Return)', 40, 44)
  doc.setFontSize(10)
  doc.text(`項目：${projectName}`, 40, 64)
  doc.text(`期間：${period}`, 40, 78)
  doc.text(`累計人次：${agg.grand}`, 40, 92)

  const head = [['日期', ...agg.trades, '每日總計']]
  const body = agg.dates.map(d => [d, ...agg.trades.map(t => String(agg.counts[d]?.[t] ?? 0)), String(agg.dateTotals[d] ?? 0)])
  body.push(['總計', ...agg.trades.map(t => String(agg.tradeTotals[t] ?? 0)), String(agg.grand)])

  autoTableFn(doc, {
    head,
    body,
    startY: 108,
    styles: { font: 'NotoHK', fontSize: 8, cellPadding: 3 },
    headStyles: { font: 'NotoHK', fillColor: [30, 64, 175], textColor: 255 },
    theme: 'grid',
  })

  // ASCII footer (jsPDF core font has no CJK; keep Latin/digits).
  doc.setFontSize(8)
  doc.text(`Generated by CK Construction · ${new Date().toISOString().slice(0, 10)}`, 40, doc.internal.pageSize.getHeight() - 20)

  const blob = doc.output('blob')
  await shareOrDownloadBlob(blob, `${safe(projectName)}_勞工人力日報_${period}.pdf`, `勞工人力日報 ${period}`)
}
