-- AUTO-GENERATED by supabase/seed-test-rig.js — do not hand-edit.
-- [TEST] permission test rig. Idempotent. Apply once.
create extension if not exists pgcrypto with schema extensions;

-- 1) auth.users
with acct(uid, phone, nm, grole, srole, pw) as (values
  ('bbbb0000-0000-0000-0000-000062000099'::uuid, '62000099', '測試管理員', 'admin', null::text, 'CKtestADMIN2026!'),
  ('bbbb0000-0000-0000-0000-000062000001'::uuid, '62000001', '測 PM', 'pm', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062000002'::uuid, '62000002', '測 老總', 'general_foreman', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062000003'::uuid, '62000003', '測 業主', 'owner', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062000004'::uuid, '62000004', '測 安全主任', 'safety_officer', 'safety'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010001'::uuid, '62010001', '一座工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010002'::uuid, '62010002', '一座管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010003'::uuid, '62010003', '一座判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010004'::uuid, '62010004', '一座工人', 'subcontractor_worker', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020001'::uuid, '62020001', '二座工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020002'::uuid, '62020002', '二座管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020003'::uuid, '62020003', '二座判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020004'::uuid, '62020004', '二座工人', 'subcontractor_worker', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030001'::uuid, '62030001', '三座工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030002'::uuid, '62030002', '三座管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030003'::uuid, '62030003', '三座判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030004'::uuid, '62030004', '三座工人', 'subcontractor_worker', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040001'::uuid, '62040001', '外圍工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040002'::uuid, '62040002', '外圍管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040003'::uuid, '62040003', '外圍判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040004'::uuid, '62040004', '外圍工人', 'subcontractor_worker', null::text, 'CKtest2026')
)
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change, email_change_token_new, email_change_token_current,
  phone_change, phone_change_token, reauthentication_token)
select a.uid, '00000000-0000-0000-0000-000000000000'::uuid, 'authenticated', 'authenticated',
  a.phone || '@phone.local', extensions.crypt(a.pw, extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(),
  '', '', '', '', '', '', '', ''
from acct a
on conflict (id) do nothing;

-- 2) auth.identities
with acct(uid, phone, nm, grole, srole, pw) as (values
  ('bbbb0000-0000-0000-0000-000062000099'::uuid, '62000099', '測試管理員', 'admin', null::text, 'CKtestADMIN2026!'),
  ('bbbb0000-0000-0000-0000-000062000001'::uuid, '62000001', '測 PM', 'pm', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062000002'::uuid, '62000002', '測 老總', 'general_foreman', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062000003'::uuid, '62000003', '測 業主', 'owner', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062000004'::uuid, '62000004', '測 安全主任', 'safety_officer', 'safety'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010001'::uuid, '62010001', '一座工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010002'::uuid, '62010002', '一座管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010003'::uuid, '62010003', '一座判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010004'::uuid, '62010004', '一座工人', 'subcontractor_worker', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020001'::uuid, '62020001', '二座工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020002'::uuid, '62020002', '二座管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020003'::uuid, '62020003', '二座判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020004'::uuid, '62020004', '二座工人', 'subcontractor_worker', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030001'::uuid, '62030001', '三座工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030002'::uuid, '62030002', '三座管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030003'::uuid, '62030003', '三座判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030004'::uuid, '62030004', '三座工人', 'subcontractor_worker', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040001'::uuid, '62040001', '外圍工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040002'::uuid, '62040002', '外圍管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040003'::uuid, '62040003', '外圍判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040004'::uuid, '62040004', '外圍工人', 'subcontractor_worker', null::text, 'CKtest2026')
)
insert into auth.identities (id, user_id, provider_id, provider, identity_data, last_sign_in_at, created_at, updated_at)
select gen_random_uuid(), a.uid, a.uid::text, 'email',
  jsonb_build_object('sub', a.uid::text, 'email', a.phone || '@phone.local', 'email_verified', true),
  now(), now(), now()
from acct a
where not exists (select 1 from auth.identities i where i.user_id = a.uid);

-- 3) user_profiles
with acct(uid, phone, nm, grole, srole, pw) as (values
  ('bbbb0000-0000-0000-0000-000062000099'::uuid, '62000099', '測試管理員', 'admin', null::text, 'CKtestADMIN2026!'),
  ('bbbb0000-0000-0000-0000-000062000001'::uuid, '62000001', '測 PM', 'pm', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062000002'::uuid, '62000002', '測 老總', 'general_foreman', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062000003'::uuid, '62000003', '測 業主', 'owner', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062000004'::uuid, '62000004', '測 安全主任', 'safety_officer', 'safety'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010001'::uuid, '62010001', '一座工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010002'::uuid, '62010002', '一座管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010003'::uuid, '62010003', '一座判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062010004'::uuid, '62010004', '一座工人', 'subcontractor_worker', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020001'::uuid, '62020001', '二座工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020002'::uuid, '62020002', '二座管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020003'::uuid, '62020003', '二座判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062020004'::uuid, '62020004', '二座工人', 'subcontractor_worker', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030001'::uuid, '62030001', '三座工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030002'::uuid, '62030002', '三座管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030003'::uuid, '62030003', '三座判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062030004'::uuid, '62030004', '三座工人', 'subcontractor_worker', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040001'::uuid, '62040001', '外圍工程師', 'main_contractor', 'engineer'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040002'::uuid, '62040002', '外圍管工', 'main_contractor', 'foreman'::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040003'::uuid, '62040003', '外圍判頭', 'subcontractor', null::text, 'CKtest2026'),
  ('bbbb0000-0000-0000-0000-000062040004'::uuid, '62040004', '外圍工人', 'subcontractor_worker', null::text, 'CKtest2026')
)
insert into user_profiles (id, phone, name, global_role, sub_role)
select a.uid, a.phone, a.nm, a.grole, a.srole from acct a
on conflict (id) do nothing;

-- 4) project [TEST] 測試大廈項目 (4 zones)
insert into projects (id, name, zones, assigned_pm_ids, created_by, project_type, ai_enabled)
values ('bbbb0000-0000-0000-0000-000000000001'::uuid, '[TEST] 測試大廈項目',
  '[{"id":"z-1","name":"一座"},{"id":"z-2","name":"二座"},{"id":"z-3","name":"三座"},{"id":"z-ext","name":"外圍"}]'::jsonb,
  array['bbbb0000-0000-0000-0000-000062000001']::uuid[], 'bbbb0000-0000-0000-0000-000062000099'::uuid, 'general', true)
on conflict (id) do nothing;

-- 5) project_members (20 approved; admin is global, not a member)
with mem(uid, mrole) as (values
  ('bbbb0000-0000-0000-0000-000062000001'::uuid, 'pm'),
  ('bbbb0000-0000-0000-0000-000062000002'::uuid, 'general_foreman'),
  ('bbbb0000-0000-0000-0000-000062000003'::uuid, 'owner'),
  ('bbbb0000-0000-0000-0000-000062000004'::uuid, 'safety_officer'),
  ('bbbb0000-0000-0000-0000-000062010001'::uuid, 'main_contractor'),
  ('bbbb0000-0000-0000-0000-000062010002'::uuid, 'main_contractor'),
  ('bbbb0000-0000-0000-0000-000062010003'::uuid, 'subcontractor'),
  ('bbbb0000-0000-0000-0000-000062010004'::uuid, 'subcontractor_worker'),
  ('bbbb0000-0000-0000-0000-000062020001'::uuid, 'main_contractor'),
  ('bbbb0000-0000-0000-0000-000062020002'::uuid, 'main_contractor'),
  ('bbbb0000-0000-0000-0000-000062020003'::uuid, 'subcontractor'),
  ('bbbb0000-0000-0000-0000-000062020004'::uuid, 'subcontractor_worker'),
  ('bbbb0000-0000-0000-0000-000062030001'::uuid, 'main_contractor'),
  ('bbbb0000-0000-0000-0000-000062030002'::uuid, 'main_contractor'),
  ('bbbb0000-0000-0000-0000-000062030003'::uuid, 'subcontractor'),
  ('bbbb0000-0000-0000-0000-000062030004'::uuid, 'subcontractor_worker'),
  ('bbbb0000-0000-0000-0000-000062040001'::uuid, 'main_contractor'),
  ('bbbb0000-0000-0000-0000-000062040002'::uuid, 'main_contractor'),
  ('bbbb0000-0000-0000-0000-000062040003'::uuid, 'subcontractor'),
  ('bbbb0000-0000-0000-0000-000062040004'::uuid, 'subcontractor_worker')
)
insert into project_members (user_id, project_id, role, status, applied_at, approved_by, approved_at)
select m.uid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, m.mrole, 'approved', now(), 'bbbb0000-0000-0000-0000-000062000099'::uuid, now()
from mem m
where not exists (select 1 from project_members pm where pm.user_id = m.uid and pm.project_id = 'bbbb0000-0000-0000-0000-000000000001'::uuid);

-- 6) progress_items (per zone: 2 大項 / 2 中項 / 4 細項; leaf assignments self-document expected viewers)
insert into progress_items (id, project_id, parent_id, code, title, zone_id, level, tracking_mode, status, assigned_to, delegated_to)
values
  ('bbbb1111-0000-0000-0000-000000000001'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, null, 'A1', '一座-上層結構〔大項〕', 'z-1', 1, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000002'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000001'::uuid, 'A1.1', '一座-結構-3樓〔中項〕', 'z-1', 2, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000003'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000002'::uuid, 'A1.1.1', '一座-3樓柱〔細項·應見:一座工程師+管工〕', 'z-1', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062010001','bbbb0000-0000-0000-0000-000062010002']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000004'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000002'::uuid, 'A1.1.2', '一座-3樓樓板〔細項·應見:一座判頭+工人〕', 'z-1', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062010003','bbbb0000-0000-0000-0000-000062010004']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000005'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, null, 'A2', '一座-機電〔大項〕', 'z-1', 1, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000006'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000005'::uuid, 'A2.1', '一座-機電-喉電〔中項〕', 'z-1', 2, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000007'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000006'::uuid, 'A2.1.1', '一座-喉管〔細項·應見:一座判頭〕', 'z-1', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062010003']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000008'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000006'::uuid, 'A2.1.2', '一座-電線〔細項·應見:一座工程師〕', 'z-1', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062010001']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000009'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, null, 'B1', '二座-上層結構〔大項〕', 'z-2', 1, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000010'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000009'::uuid, 'B1.1', '二座-結構-3樓〔中項〕', 'z-2', 2, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000011'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000010'::uuid, 'B1.1.1', '二座-3樓柱〔細項·應見:二座工程師+管工〕', 'z-2', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062020001','bbbb0000-0000-0000-0000-000062020002']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000012'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000010'::uuid, 'B1.1.2', '二座-3樓樓板〔細項·應見:二座判頭+工人〕', 'z-2', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062020003','bbbb0000-0000-0000-0000-000062020004']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000013'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, null, 'B2', '二座-機電〔大項〕', 'z-2', 1, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000014'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000013'::uuid, 'B2.1', '二座-機電-喉電〔中項〕', 'z-2', 2, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000015'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000014'::uuid, 'B2.1.1', '二座-喉管〔細項·應見:二座判頭〕', 'z-2', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062020003']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000016'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000014'::uuid, 'B2.1.2', '二座-電線〔細項·應見:二座工程師〕', 'z-2', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062020001']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000017'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, null, 'C1', '三座-上層結構〔大項〕', 'z-3', 1, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000018'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000017'::uuid, 'C1.1', '三座-結構-3樓〔中項〕', 'z-3', 2, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000019'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000018'::uuid, 'C1.1.1', '三座-3樓柱〔細項·應見:三座工程師+管工〕', 'z-3', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062030001','bbbb0000-0000-0000-0000-000062030002']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000020'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000018'::uuid, 'C1.1.2', '三座-3樓樓板〔細項·應見:三座判頭+工人〕', 'z-3', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062030003','bbbb0000-0000-0000-0000-000062030004']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000021'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, null, 'C2', '三座-機電〔大項〕', 'z-3', 1, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000022'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000021'::uuid, 'C2.1', '三座-機電-喉電〔中項〕', 'z-3', 2, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000023'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000022'::uuid, 'C2.1.1', '三座-喉管〔細項·應見:三座判頭〕', 'z-3', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062030003']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000024'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000022'::uuid, 'C2.1.2', '三座-電線〔細項·應見:三座工程師〕', 'z-3', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062030001']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000025'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, null, 'D1', '外圍-上層結構〔大項〕', 'z-ext', 1, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000026'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000025'::uuid, 'D1.1', '外圍-結構-3樓〔中項〕', 'z-ext', 2, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000027'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000026'::uuid, 'D1.1.1', '外圍-3樓柱〔細項·應見:外圍工程師+管工〕', 'z-ext', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062040001','bbbb0000-0000-0000-0000-000062040002']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000028'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000026'::uuid, 'D1.1.2', '外圍-3樓樓板〔細項·應見:外圍判頭+工人〕', 'z-ext', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062040003','bbbb0000-0000-0000-0000-000062040004']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000029'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, null, 'D2', '外圍-機電〔大項〕', 'z-ext', 1, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000030'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000029'::uuid, 'D2.1', '外圍-機電-喉電〔中項〕', 'z-ext', 2, 'percentage', 'not-started', '{}'::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000031'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000030'::uuid, 'D2.1.1', '外圍-喉管〔細項·應見:外圍判頭〕', 'z-ext', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062040003']::uuid[], '{}'::uuid[]),
  ('bbbb1111-0000-0000-0000-000000000032'::uuid, 'bbbb0000-0000-0000-0000-000000000001'::uuid, 'bbbb1111-0000-0000-0000-000000000030'::uuid, 'D2.1.2', '外圍-電線〔細項·應見:外圍工程師〕', 'z-ext', 3, 'percentage', 'not-started', array['bbbb0000-0000-0000-0000-000062040001']::uuid[], '{}'::uuid[])
on conflict (id) do nothing;
